from django.urls import path
from . import views
urlpatterns = [
    path("iniciar_sesion", views.inicio_sesion),
    path("tipos-usuario", views.obtener_tipos_usuario),
    path("register", views.registrar_usuario, name="registrar_usuario"),
    path("planesRecojo", views.obtener_planes_recojo),
    path("planes/<int:usuario_id>/",views.obtener_plan_usuario),
    path("cupones", views.obtener_cupons),
    path("canjear_cupon", views.canjear_cupon),
    path('guardar_cambio_contrasena', views.guardar_cambio_contrasena),
    path('crear_pago', views.crear_pago, name='crear_pago'),
    path('guardar_perfil', views.guardar_perfil),
    path('gestor_plan', views.crear_gestor_plan),
    path('solicitar_recojo', views.iniciar_recojo),
    path('cancelar_recojo', views.cancelar_recojo),
    path('estado_pedido', views.verificar_trayectoria_recojo),
    path('obtener_recojos/<int:administrador_id>/', views.obtener_recojos),
    path('historial_recojos/<int:usuario_id>/', views.obtener_recojos_por_administrador),
    path('historial_codigos/<int:usuario_id>/', views.obtener_codigos_invitacion),     
    path('puntos/<int:usuario_id>/', views.obtener_puntaje_usuario, name='obtener_puntaje_usuario'),
    path('consultar_recojo', views.consultar_recojo),
    path('generar', views.generar_codigo_invitacion),
    path('enviarEmail', views.send_email),
    path('enviar_token', views.enviar_token,name='enviar_token'),
    path('cambiar_contrasena', views.cambiar_contrasena,name='cambiar_contrasena'),
    path('historial_cupones/<int:usuario_id>/', views.obtener_historial_cupones),
    path('obtener_recojosus/<int:usuario_id>/', views.obtener_recojosus),
    path('retroceder_estado', views.consultar_recojoR),
    path('verificar_recojo_activo/<int:usuario_id>/', views.verificar_recojo_activo),
    path('listar_pagos_no_validados/', views.listar_pagos_no_validados, name='listar_pagos_no_validados'),
    path('validar_pago/<int:pago_id>/', views.validar_pago, name='validar_pago'),
    path('enviar_PDF', views.enviar_PDF),
    path('notificaciones', views.ultimas_notificaciones),
    path('no_leidas', views.obtener_notificaciones_no_leidas),
    path('marcar-leidas', views.marcar_notificaciones_como_leidas)
    ]