# Generated by Django 5.1.1 on 2024-09-30 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', 'data001'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRecojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('materiales', models.CharField(max_length=30)),
                ('frecuencia_recojo', models.IntegerField()),
                ('cantidad_compostaje', models.FloatField()),
                ('puntos_plan', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='cupon',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='estadoservicio',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cantidad_residuos_acumulados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.cliente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='puntos',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.planrecojo'),
        ),
        migrations.AlterField(
            model_name='serviciocompostaje',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.planrecojo'),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
