# Generated by Django 5.1.1 on 2024-10-03 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', 'data001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trayectoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='serviciocompostaje',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='puntos',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='cupon',
            name='puntos',
        ),
        migrations.RemoveField(
            model_name='serviciocompostaje',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='serviciocompostaje',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='cupon',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='materiales',
        ),
        migrations.AddField(
            model_name='plan',
            name='aserrin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='baldes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.pago'),
        ),
        migrations.AddField(
            model_name='plan',
            name='puntos_plan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='DNI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_contacto',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='plan',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cantidad_residuos_acumulados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='puntaje_acumulado',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Recojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.plan')),
                ('trayectoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.trayectoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='EstadoServicio',
        ),
        migrations.DeleteModel(
            name='Puntos',
        ),
        migrations.DeleteModel(
            name='ServicioCompostaje',
        ),
    ]
