# Generated by Django 5.1.1 on 2024-09-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_planrecojo_alter_cupon_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='puntaje_acumulado',
            field=models.IntegerField(default=0),
        ),
    ]
