# Generated by Django 5.1.1 on 2024-10-03 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_tipo_usuario_trayectoria_remove_usuario_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='pago',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipousuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.tipo_usuario'),
        ),
        migrations.CreateModel(
            name='GestorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.pago')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.plan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.usuario')),
            ],
        ),
    ]
