# Generated by Django 5.1.1 on 2024-10-01 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alter_usuario_contrasena_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cupon',
            name='puntos',
        ),
        migrations.RemoveField(
            model_name='cupon',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='serviciocompostaje',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='serviciocompostaje',
            name='usuario',
        ),
        migrations.AddField(
            model_name='planrecojo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.usuario'),
        ),
        migrations.AddField(
            model_name='serviciocompostaje',
            name='pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.pago'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='GestorCupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.cupon')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Puntos',
        ),
    ]
