# Generated by Django 5.1.1 on 2024-10-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_alter_recojo_trayectoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trayectoria',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
