# Generated by Django 5.1.1 on 2024-10-02 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_administrador_remove_cupon_puntos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planrecojo',
            name='materiales',
        ),
        migrations.RemoveField(
            model_name='planrecojo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='planrecojo',
            name='aserrin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planrecojo',
            name='baldes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planrecojo',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviciocompostaje',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.planrecojo'),
        ),
        migrations.CreateModel(
            name='GestorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.planrecojo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.usuario')),
            ],
        ),
    ]
