# Generated by Django 5.1.1 on 2024-10-03 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_trayectoria_fecha_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trayectoria',
            name='fecha_fin',
        ),
    ]
