# Generated by Django 5.1.1 on 2024-10-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_remove_trayectoria_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='trayectoria',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
