# Generated by Django 5.1.1 on 2024-10-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_trayectoria_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_usuario',
            name='tipo',
            field=models.CharField(max_length=15),
        ),
    ]
