# Generated by Django 5.1.1 on 2024-10-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='imagen',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='imagen',
            field=models.URLField(),
        ),
    ]
