# Generated by Django 5.1.1 on 2024-10-08 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_remove_recojo_plan_recojo_gestor_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recojo_trayectoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_ingreso', models.DateField()),
                ('recojo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.recojo')),
                ('trayectoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.trayectoria')),
            ],
        ),
    ]
