# Generated by Django 5.1.1 on 2024-10-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_recojo_trayectoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recojo',
            name='trayectoria',
        ),
    ]
