# Generated by Django 5.1.1 on 2024-10-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0012_remove_recojo_trayectoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trayectoria',
            name='fecha_fin',
        ),
        migrations.AlterField(
            model_name='trayectoria',
            name='estado',
            field=models.IntegerField(),
        ),
    ]
