# Generated by Django 5.1.1 on 2024-10-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_remove_trayectoria_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trayectoria',
            name='estado',
            field=models.CharField(max_length=2),
        ),
    ]
