# Generated by Django 5.1.1 on 2024-10-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0014_alter_trayectoria_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recojo_trayectoria',
            name='estado_ingreso',
            field=models.DateTimeField(),
        ),
    ]
