# Generated by Django 5.1.1 on 2024-10-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0015_alter_recojo_trayectoria_estado_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestorplan',
            name='recojos_solicitados',
            field=models.IntegerField(default=0),
        ),
    ]
