# Generated by Django 5.1.1 on 2024-10-25 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0018_remove_usuario_cantidad_residuos_acumulados_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recojo_trayectoria',
            old_name='usuario',
            new_name='administrador',
        ),
    ]
