# Generated by Django 5.1.1 on 2024-10-30 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0019_rename_usuario_recojo_trayectoria_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='gestorcupon',
            name='codigoQR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.codigoqr'),
        ),
    ]
