# Generated by Django 5.1.1 on 2024-11-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0022_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestorcupon',
            name='fecha_canje',
            field=models.DateField(blank=True, null=True),
        ),
    ]
