# Generated by Django 5.1.1 on 2024-11-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0023_gestorcupon_fecha_canje'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestorplan',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
