# Generated by Django 5.1.1 on 2024-11-21 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0024_gestorplan_validado_pago_monto_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestorcupon',
            name='nombre_cupon',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='gestorplan',
            name='nombre_plan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gestorplan',
            name='puntos_backup',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gestorcupon',
            name='cupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.cupon'),
        ),
        migrations.AlterField(
            model_name='gestorplan',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.plan'),
        ),
        migrations.AlterField(
            model_name='recojo',
            name='gestor_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.gestorplan'),
        ),
        migrations.AlterField(
            model_name='recojo_trayectoria',
            name='administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.usuario'),
        ),
    ]
