# Generated by Django 5.1.1 on 2024-11-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0025_token_tipo_alter_token_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto',
            field=models.FloatField(null=True),
        ),
    ]
