# Generated by Django 5.1.1 on 2024-11-13 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0026_pago_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='tipo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.usuario'),
        ),
    ]
