# Generated by Django 5.1.1 on 2024-11-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0027_alter_token_tipo_alter_token_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='tipo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
