# Generated by Django 5.1.1 on 2024-11-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0029_remove_token_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='monto',
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_pago',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='token',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
