# Generated by Django 5.1.1 on 2024-11-21 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0036_alter_notificacion_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestorcupon',
            name='cupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.cupon'),
        ),
        migrations.AlterField(
            model_name='gestorplan',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.plan'),
        ),
        migrations.AlterField(
            model_name='recojo',
            name='gestor_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.gestorplan'),
        ),
        migrations.AlterField(
            model_name='recojo_trayectoria',
            name='administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.usuario'),
        ),
    ]
