# Generated by Django 5.1.1 on 2024-11-21 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0037_alter_gestorcupon_cupon_alter_gestorplan_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recojo',
            name='gestor_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.gestorplan'),
        ),
    ]
