# Generated by Django 5.1.1 on 2024-11-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0038_alter_recojo_gestor_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestorcupon',
            name='nombre_cupon',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gestorplan',
            name='nombre_plan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
