# Generated by Django 5.1.1 on 2024-11-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0039_gestorcupon_nombre_cupon_gestorplan_nombre_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestorcupon',
            name='nombre_cupon',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
