# Generated by Django 5.1.1 on 2024-11-21 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0040_alter_gestorcupon_nombre_cupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recojo',
            name='gestor_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.gestorplan'),
        ),
    ]
