# Generated by Django 5.1.1 on 2024-11-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0041_alter_recojo_gestor_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestorplan',
            name='puntos_backup',
            field=models.IntegerField(null=True),
        ),
    ]
