# Generated by Django 5.1.1 on 2024-11-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0042_gestorplan_puntos_backup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=130, null=True),
        ),
    ]
